fix onValueChanges is called on programmatic value changes on Android
callstack/react-native-slider pull request #409
Opened 2022-08-01 11:32 UTC by minhtc

Summary:
---------

Revert changes from https://github.com/callstack/react-native-slider/pull/367 to fix https://github.com/callstack/react-native-slider/issues/395

2022-08-01 13:30 UTC, BartoszKlonowski requested changes
Intuitively the `onValueChange` should be called also when user taps on Slider, as tapping also changes the value, I think it's the mistake of mine that we have the opposite written in the docs.
I think that instead of reverting the fix of one to fix another we should create an issue about the lack of `onValueChange` on iOS and work on a decent fix for the current issue keeping the backward compatibility.

2022-08-02 07:31 UTC, minhtc commented
> Intuitively the `onValueChange` should be called also when user taps on Slider, as tapping also changes the value, I think it's the mistake of mine that we have the opposite written in the docs.
> I think that instead of reverting the fix of one to fix another we should create an issue about the lack of `onValueChange` on iOS and work on a decent fix for the current issue keeping the backward compatibility.

If the `onValueChange` event is always be called, I think it should send with an extra flag to know if it is from dragging or tapping.
In my case, I need to check if the slider value is changed from dragging action to prevent some performance issue. If the slider value is changed by set the `value` prop, I do not need `onValueChange` because I already know the value.

2022-08-02 21:42 UTC, jeffmon commented
Sorry if this is not applicable here, but using the latest version `"@react-native-community/slider": "^4.2.4"`, `onValueChange` still fires automatically when the scrubber first starts up.

2022-09-28 00:33 UTC, Dev-Grey approved these changes

2022-09-29 09:30 UTC, closed without merging

2023-01-02 18:33 UTC, laurent22 commented
Also still happening in react-native-community/slider@4.4.0