[Fabric] Refactor events, remove unused code
callstack/react-native-slider pull request #422
Opened 2022-08-29 16:29 UTC by okwasniewski

Summary:
---------

According to [this discussion](https://github.com/reactwg/react-native-new-architecture/discussions/70#discussioncomment-3429973), ShadowNodes are not used in the new architecture so I moved it back to old arch. 

Regarding events: 

> `RCTModernEventEmitter` is a transitional replacement for `RCTEventEmitter` that works with Fabric and non-Fabric renderers. `RCTEventEmitter` works with Fabric as well, but there are negative perf implications and it should be avoided.

Source: [react-native source code](https://github.dev/facebook/react-native/blob/e0a71fc7b5cb8c264000147099be5b2575931193/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/RCTModernEventEmitter.java#L7)

Test Plan:
----------
CI

2022-08-29 16:31 UTC, thymikee approved these changes

2022-08-30 06:53 UTC, troZee requested changes

2022-08-30 06:53 UTC, troZee commented on package/android/src/newarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
> -  @Override
Have we got a plan to adapt those Shadow Nodes to new arch https://github.com/facebook/react-native/blob/0.70-stable/ReactCommon/react/renderer/components/slider/SliderShadowNode.cpp ?

2022-08-30 07:23 UTC, troZee approved these changes

2022-09-06 21:32 UTC, BartoszKlonowski approved these changes
Ready to merge as soon as indents are corrected 👍

2022-09-06 21:32 UTC, BartoszKlonowski commented on package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
> +        private int mWidth;
Please keep the same indents across files, here should be 2 spaces.

2022-09-06 21:32 UTC, BartoszKlonowski commented on package/android/src/main/java/com/reactnativecommunity/slider/ReactSliderEvent.java
> +      rctEventEmitter.receiveEvent(getViewTag(), getEventName(), serializeEventData());
Extra and unnecessary diff - please remove the incorrect indent and keep 2 spaces.

2022-09-07 20:35 UTC, merged