fix: new arch android interface
callstack/react-native-slider pull request #654
Opened 2024-10-08 07:22 UTC by draggie

Summary:
fix: #652 
Resolved incompatible interface generation for the codegen source.
Tmp patch for invalid height calculation 
---------

Test Plan:
----------

2024-10-08 09:30 UTC, vonovak reviewed
I didn't run the code but it looks okay to me, just added a comment about using doubles.

re "Tmp patch for invalid height calculation" in the description: that doesn't seem to be included

2024-10-10 06:47 UTC, draggie commented
@vonovak Thanks, I have removed the tmp solution from the description as after further investigation this issue is related to `measure` function from `ViewManager` not being called in some setups like RNTA

2024-10-10 11:45 UTC, vonovak requested changes

2024-10-10 11:45 UTC, vonovak commented on package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
> +  @ReactProp(name = "maximumValue", defaultDouble = 1f)
```suggestion
  @ReactProp(name = "maximumValue", defaultDouble = 1d)
```

2024-10-10 11:45 UTC, vonovak commented on package/android/src/oldarch/java/com/reactnativecommunity/slider/ReactSliderManager.java
> +  @ReactProp(name = "step", defaultDouble = 0f)
```suggestion
  @ReactProp(name = "step", defaultDouble = 0d)
```

2024-10-10 12:21 UTC, chrfalch commented
Me and @vonovak made #657 - which might solve the root cause of the problem.

2024-10-10 13:54 UTC, okwasniewski approved these changes

2024-10-14 15:16 UTC, BartoszKlonowski approved these changes

2024-10-14 15:20 UTC, merged